services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/delivery-app
      - PORT=3000
      # Set to false for standalone MongoDB (no replica set)
      - USE_MONGODB_TRANSACTIONS=false
    restart: always
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      # Using simplified initialization script
      - ./docker/mongo-init-simple.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # Standard MongoDB without replica set
    environment:
      - MONGO_INITDB_DATABASE=delivery-app
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
